"""
monitoring/management/commands/seed_demo_data.py

Usage:
    python manage.py seed_demo_data
    python manage.py seed_demo_data --flush   # wipes existing demo data first

Creates a realistic spread of MSMEs and projects across every status,
covering the scenarios you'd actually want to click through while testing:
  - a stalled pending application (>1 year old — is_pending_delinquent)
  - a Phase I project running late (is_phase1_delayed)
  - a Phase II project that's current on payments
  - a Phase II project a few months behind (is_refund_delinquent)
  - a Phase II project 6+ months behind (the collection-action threshold)
  - a Phase II project that's been restructured
  - a Phase II project that's nearly fully refunded
  - completed, terminated, and withdrawn projects
  - two MSMEs that are deliberately INELIGIBLE for new iFund (one for
    outstanding accountabilities, one for Filipino ownership under 60%)
    so Cooperator.is_eligible_for_new_ifund has something to actually flag

Deliberately does NOT hand-create ProjectRequirement rows — those are
auto-generated by monitoring/signals.py the moment a project is created or
advances a phase, exactly as they would be for a real project. This command
instead marks a realistic subset of the auto-created rows as submitted, and
steps each project through its real status sequence via .save() calls (not
a single field assignment) so the refund-schedule-generation signal fires
naturally too.

File fields (photo, requirement/report files, receipts, supporting
documents) are deliberately left EMPTY — attaching and testing file uploads
is exactly the kind of thing you'll want to click through by hand in the
running app, not something worth faking with placeholder bytes here.
"""

import random
from datetime import timedelta
from decimal import Decimal

from dateutil.relativedelta import relativedelta
from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand
from django.db import transaction
from django.utils import timezone

from monitoring.models import (
    Cooperator, Project, BudgetLineItem, BudgetRealignment,
    RefundInstallment, RefundPayment, RefundRestructure,
    Equipment, MonitoringReport, ImpactRecord,
)

random.seed(43)  # reproducible output — rerun and get the same demo data

TODAY = timezone.now().date()


# ---------------------------------------------------------------------------
# MSMEs
# ---------------------------------------------------------------------------

COOPERATORS = [
    dict(
        name="Koronadal Root Crops Processing Cooperative",
        business_type="cooperative", enterprise_category="small", development_stage="growing",
        priority_sector="Food Processing", address="Koronadal City, South Cotabato",
        contact_person="Elena Bautista", contact_number="0917-100-1001", email="krcpc@example.com",
        dti_sec_cda_registration_no="CDA-2019-00123", filipino_ownership_percent=Decimal("100.00"),
        has_outstanding_accountabilities=False, is_export_firm=False,
    ),
    dict(
        name="GenSan Tuna Producers Association",
        business_type="industry_association", enterprise_category="medium", development_stage="expanding",
        priority_sector="Fisheries and Aquaculture", address="General Santos City",
        contact_person="Ramil Dizon", contact_number="0917-100-1002", email="gensantuna@example.com",
        dti_sec_cda_registration_no="SEC-2015-04455", filipino_ownership_percent=Decimal("100.00"),
        has_outstanding_accountabilities=False, is_export_firm=True,
    ),
    dict(
        name="Lake Sebu Handloom Weavers MPC",
        business_type="cooperative", enterprise_category="micro", development_stage="developing",
        priority_sector="Handicrafts and Weaving", address="Lake Sebu, South Cotabato",
        contact_person="Maria Fatima Guiabar", contact_number="0917-100-1003", email="lakesebuweavers@example.com",
        dti_sec_cda_registration_no="CDA-2021-00987", filipino_ownership_percent=Decimal("100.00"),
        has_outstanding_accountabilities=False, is_export_firm=False,
    ),
    dict(
        name="Sarangani Cacao Farmers Cooperative",
        business_type="cooperative", enterprise_category="small", development_stage="growing",
        priority_sector="Agri-processing (Cacao)", address="Alabel, Sarangani",
        contact_person="Joel Ramos", contact_number="0917-100-1004", email="saranganicacao@example.com",
        dti_sec_cda_registration_no="CDA-2018-00541", filipino_ownership_percent=Decimal("100.00"),
        has_outstanding_accountabilities=False, is_export_firm=True,
    ),
    dict(
        name="Tacurong Furniture Works Inc.",
        business_type="corporation", enterprise_category="small", development_stage="growing",
        priority_sector="Furniture and Woodcraft", address="Tacurong City, Sultan Kudarat",
        contact_person="Antonio Villareal", contact_number="0917-100-1005", email="tacurongfurniture@example.com",
        dti_sec_cda_registration_no="SEC-2017-02233", filipino_ownership_percent=Decimal("100.00"),
        has_outstanding_accountabilities=False, is_export_firm=False,
    ),
    dict(
        # Deliberately INELIGIBLE — has_outstanding_accountabilities=True
        name="Sultan Kudarat Rubber Producers Coop",
        business_type="cooperative", enterprise_category="medium", development_stage="expanding",
        priority_sector="Rubber Processing", address="Isulan, Sultan Kudarat",
        contact_person="Herminia Cruz", contact_number="0917-100-1006", email="skrubber@example.com",
        dti_sec_cda_registration_no="CDA-2014-00219", filipino_ownership_percent=Decimal("100.00"),
        has_outstanding_accountabilities=True, is_export_firm=True,
    ),
    dict(
        name="Polomolok Pineapple Byproducts Enterprise",
        business_type="sole_proprietorship", enterprise_category="micro", development_stage="developing",
        priority_sector="Agri-processing (Pineapple Byproducts)", address="Polomolok, South Cotabato",
        contact_person="Ricardo Mangubat", contact_number="0917-100-1007", email="polopineapple@example.com",
        dti_sec_cda_registration_no="DTI-2022-11209", filipino_ownership_percent=Decimal("100.00"),
        has_outstanding_accountabilities=False, is_export_firm=False,
    ),
    dict(
        name="Banga Metal Fabrication Services",
        business_type="sole_proprietorship", enterprise_category="small", development_stage="growing",
        priority_sector="Metals and Engineering", address="Banga, South Cotabato",
        contact_person="Danilo Reyes", contact_number="0917-100-1008", email="bangametal@example.com",
        dti_sec_cda_registration_no="DTI-2020-05567", filipino_ownership_percent=Decimal("100.00"),
        has_outstanding_accountabilities=False, is_export_firm=False,
    ),
    dict(
        # Deliberately INELIGIBLE — Filipino ownership below the 60% floor
        name="Isulan Native Delicacies Producers",
        business_type="partnership", enterprise_category="micro", development_stage="developing",
        priority_sector="Food Processing", address="Isulan, Sultan Kudarat",
        contact_person="Grace Palad", contact_number="0917-100-1009", email="isulandelicacies@example.com",
        dti_sec_cda_registration_no="DTI-2023-00845", filipino_ownership_percent=Decimal("55.00"),
        has_outstanding_accountabilities=False, is_export_firm=False,
    ),
    dict(
        name="Surallah Organic Farmers Association",
        business_type="industry_association", enterprise_category="small", development_stage="growing",
        priority_sector="Organic Agriculture", address="Surallah, South Cotabato",
        contact_person="Noel Aquino", contact_number="0917-100-1010", email="surallahorganic@example.com",
        dti_sec_cda_registration_no="SEC-2019-03321", filipino_ownership_percent=Decimal("100.00"),
        has_outstanding_accountabilities=False, is_export_firm=True,
    ),
]


# ---------------------------------------------------------------------------
# Projects — one blueprint per project. `coop` is an index into COOPERATORS.
# `scenario` drives which extra setup helper runs (payments, restructure, etc).
# ---------------------------------------------------------------------------

PROJECT_BLUEPRINTS = [
    dict(coop=0, title="Cassava Chips Processing Line", target="phase_2", scenario="healthy",
         amount=Decimal("480000.00"), fund_source="setup_budget", refund_years=3, jobs=6),
    dict(coop=0, title="Root Crop Flour Milling Expansion", target="phase_1", scenario="on_track",
         amount=Decimal("350000.00"), fund_source="setup_budget", jobs=4),
    dict(coop=1, title="Tuna Canning Line Upgrade", target="phase_2", scenario="mild_delinquent",
         amount=Decimal("950000.00"), fund_source="setup_budget", refund_years=5, jobs=12),
    dict(coop=1, title="Cold Storage Facility Application", target="pending", scenario="fresh",
         amount=Decimal("620000.00"), fund_source="lgia", jobs=0),
    dict(coop=2, title="Handloom Weaving Equipment Set", target="phase_1", scenario="on_track",
         amount=Decimal("180000.00"), fund_source="setup_budget", jobs=3),
    dict(coop=3, title="Cacao Fermentation and Drying Facility", target="completed", scenario="closed_out",
         amount=Decimal("420000.00"), fund_source="setup_budget", refund_years=3, jobs=5),
    dict(coop=3, title="Cacao Grinder and Roaster Upgrade", target="phase_2", scenario="nearly_paid",
         amount=Decimal("300000.00"), fund_source="setup_budget", refund_years=3, jobs=4),
    dict(coop=4, title="CNC Wood Router Acquisition", target="phase_2", scenario="restructured",
         amount=Decimal("540000.00"), fund_source="setup_budget", refund_years=5, jobs=7),
    dict(coop=5, title="Rubber Sheet Processing Plant", target="terminated", scenario="terminated",
         amount=Decimal("710000.00"), fund_source="setup_budget", jobs=0),
    dict(coop=6, title="Pineapple Fiber Extraction Unit", target="pending", scenario="stalled",
         amount=Decimal("260000.00"), fund_source="setup_budget", jobs=0),
    dict(coop=7, title="Metal Fabrication Workshop Tools", target="phase_1", scenario="delayed",
         amount=Decimal("310000.00"), fund_source="setup_budget", jobs=3),
    dict(coop=8, title="Native Delicacies Packaging Line", target="withdrawn", scenario="withdrawn",
         amount=Decimal("150000.00"), fund_source="setup_budget", jobs=0),
    dict(coop=9, title="Organic Fertilizer Production Facility", target="phase_2", scenario="heavy_delinquent",
         amount=Decimal("530000.00"), fund_source="setup_budget", refund_years=3, jobs=6),
    dict(coop=9, title="Seed Bank and Nursery Support", target="completed", scenario="closed_out",
         amount=Decimal("275000.00"), fund_source="lgia", refund_years=3, jobs=2),
    dict(coop=2, title="Natural Dye Extraction Facility", target="pending", scenario="fresh",
         amount=Decimal("140000.00"), fund_source="setup_budget", jobs=0),
]


class Command(BaseCommand):
    help = "Seeds realistic demo data (MSMEs, projects, refunds, budgets, reports, impact figures, test accounts)."

    def add_arguments(self, parser):
        parser.add_argument(
            '--flush', action='store_true',
            help="Delete existing Cooperators/Projects (and everything that cascades from them) before seeding.",
        )

    def handle(self, *args, **options):
        with transaction.atomic():
            if options['flush']:
                self._flush()
            cooperators = self._create_cooperators()
            for blueprint in PROJECT_BLUEPRINTS:
                self._create_project(blueprint, cooperators[blueprint['coop']])
            self._create_impact_records()
            self._create_demo_users()

        self.stdout.write(self.style.SUCCESS(
            f"\nDone — {len(cooperators)} MSMEs, {len(PROJECT_BLUEPRINTS)} projects, "
            f"4 quarters of Impact KPI data seeded."
        ))

    # -- Cleanup --------------------------------------------------------------

    def _flush(self):
        self.stdout.write("Flushing existing demo data...")
        # Projects cascade-delete everything hanging off them (budget items,
        # installments, payments, equipment, reports, requirements). Cooperator
        # is PROTECT, so projects must go first.
        Project.objects.all().delete()
        Cooperator.objects.all().delete()
        ImpactRecord.objects.all().delete()

    # -- MSMEs ------------------------------------------------------------------

    def _create_cooperators(self):
        self.stdout.write("Creating MSMEs...")
        cooperators = []
        for data in COOPERATORS:
            # update_or_create (not get_or_create) so editing an MSME's data
            # in COOPERATORS and rerunning without --flush actually applies
            # the change — get_or_create's `defaults` only ever apply on
            # creation, so a pre-existing row would silently keep its old
            # field values forever otherwise.
            data_without_name = {k: v for k, v in data.items() if k != 'name'}
            coop, _ = Cooperator.objects.update_or_create(name=data['name'], defaults=data_without_name)
            cooperators.append(coop)
        return cooperators

    # -- Projects ---------------------------------------------------------------

    def _create_project(self, blueprint, cooperator):
        self.stdout.write(f"  Creating project: {blueprint['title']} ({blueprint['target']}/{blueprint['scenario']})")

        project = Project.objects.create(
            cooperator=cooperator,
            title=blueprint['title'],
            project_code=self._next_project_code(),
            total_ifund_amount=blueprint['amount'],
            fund_source=blueprint['fund_source'],
            refund_period_years=blueprint.get('refund_years'),
            jobs_created=blueprint['jobs'],
        )
        # ^ created at status=PENDING (the model default) — creating this
        # fires create_default_requirements, populating the Phase I gate
        # checklist exactly as it would for a real new application.

        scenario = blueprint['scenario']

        if scenario == 'fresh':
            return  # stays pending, nothing further to do

        if scenario == 'stalled':
            # Backdate created_at so is_pending_delinquent (>1 year in
            # PENDING) actually trips — created_at is auto_now_add, so it
            # has to be fixed up with a direct .update() after the fact.
            Project.objects.filter(pk=project.pk).update(
                created_at=timezone.now() - relativedelta(years=1, months=2)
            )
            return

        # --- Everything past this point has at least reached Phase I ---
        if scenario == 'delayed':
            phase1_start = TODAY - relativedelta(months=10)
            expected_months = 6  # window already elapsed -> is_phase1_delayed trips
        else:
            phase1_start = TODAY - relativedelta(months=3)
            expected_months = 9  # window still open -> not delayed
        project.phase1_start_date = phase1_start
        project.phase1_expected_end_date = phase1_start + relativedelta(months=expected_months)
        project.save()

        self._advance(project, Project.Status.PHASE_1)
        # ^ fires create_next_phase_requirements, pre-populating the Phase II
        # gate checklist even though the project hasn't gotten there yet —
        # matches real signal behavior.
        self._mark_requirements(project, Project.Status.PHASE_1, fraction=1.0, as_of=phase1_start + timedelta(days=10))
        self._add_budget_and_equipment(project)

        if scenario == 'delayed':
            # Expected end date already passed, no actual end date set —
            # this is exactly what Project.is_phase1_delayed checks for.
            self._add_monitoring_reports(project)
            return

        if scenario == 'on_track':
            self._add_monitoring_reports(project)
            return

        if scenario == 'terminated':
            project.termination_reason = Project.TerminationReason.COOPERATOR_DEFAULT
            project.termination_date = TODAY - timedelta(days=30)
            project.status = Project.Status.TERMINATED
            project.save()
            self._add_monitoring_reports(project)
            return

        if scenario == 'withdrawn':
            project.termination_date = TODAY - timedelta(days=15)
            project.status = Project.Status.WITHDRAWN
            project.save()
            self._add_monitoring_reports(project)
            return

        # --- Everything past this point enters Phase II ---
        project.phase1_actual_end_date = project.phase1_expected_end_date - timedelta(days=5)

        months_since_refund_start = {
            'healthy': 4, 'mild_delinquent': 7, 'heavy_delinquent': 10,
            'restructured': 5, 'nearly_paid': (blueprint.get('refund_years') or 3) * 12 - 2,
            'closed_out': (blueprint.get('refund_years') or 3) * 12 + 1,
        }[scenario]
        project.refund_start_date = TODAY - relativedelta(months=months_since_refund_start)
        project.save()

        self._advance(project, Project.Status.PHASE_2)
        # ^ fires _generate_refund_schedule (creates the full installment
        # schedule from refund_start_date/refund_period_years/total_ifund_amount)
        # AND create_next_phase_requirements (pre-populates the Completed gate).
        self._mark_requirements(
            project, Project.Status.PHASE_2, fraction=1.0,
            as_of=project.phase1_actual_end_date + timedelta(days=5),
        )

        paid_counts = {
            'healthy': 4, 'mild_delinquent': 2, 'heavy_delinquent': 0,
            'restructured': 3, 'nearly_paid': months_since_refund_start,
            'closed_out': project.refund_installments.count(),  # pay off everything
        }
        self._pay_installments(project, paid_counts[scenario])

        if scenario == 'restructured':
            RefundRestructure.objects.create(
                project=project,
                ground=RefundRestructure.Ground.TECHNICAL,
                requested_date=TODAY - timedelta(days=45),
                new_schedule_notes="Seed data — equipment downtime pushed back the repayment capacity for one quarter.",
                approved=True,
                approved_date=TODAY - timedelta(days=30),
            )

        self._add_monitoring_reports(project)

        if scenario == 'closed_out':
            self._mark_requirements(
                project, Project.Status.COMPLETED, fraction=1.0, as_of=TODAY - timedelta(days=10),
            )
            self._advance(project, Project.Status.COMPLETED)
            self._add_monitoring_reports(project)  # adds the terminal report too

    _project_code_seq = 0

    def _next_project_code(self):
        # Placeholder numbering only — DOST SARGEN's real project-code
        # convention hasn't been decided yet (see project backlog). Swap
        # this out once that's settled.
        self.__class__._project_code_seq += 1
        return f"SETUP-{TODAY.year}-{self.__class__._project_code_seq:04d}"

    @staticmethod
    def _advance(project, status):
        """Step status forward via a real .save() (not skipping straight to
        the target) so every signal tied to a genuine transition fires."""
        project.status = status
        project.save()

    @staticmethod
    def _mark_requirements(project, phase, fraction, as_of):
        reqs = list(project.requirements.filter(phase=phase))
        random.shuffle(reqs)
        n = round(len(reqs) * fraction)
        for req in reqs[:n]:
            req.is_submitted = True
            req.date_submitted = as_of
            req.remarks = "Seed data — marked submitted (no file attached)"
            req.save()

    @staticmethod
    def _pay_installments(project, count):
        """Marks the first `count` chronological unpaid installments PAID,
        creating a matching RefundPayment for each — a real paper trail,
        not just a flipped status flag."""
        installments = project.refund_installments.filter(
            status=RefundInstallment.Status.UNPAID
        ).order_by('due_date')[:count]
        for inst in installments:
            inst.status = RefundInstallment.Status.PAID
            inst.save(update_fields=['status'])
            RefundPayment.objects.create(
                project=project, installment=inst, amount_paid=inst.amount_due,
                date_paid=inst.due_date + timedelta(days=random.randint(0, 5)),
                or_number=f"OR-{project.pk}-{inst.pk}",
                remarks="Seed data — simulated payment",
            )

    @staticmethod
    def _add_budget_and_equipment(project):
        total = project.total_ifund_amount
        splits = [Decimal("0.60"), Decimal("0.25"), Decimal("0.15")]
        categories = ['equipment', 'training', 'lab_analysis']
        remaining = total
        for i, frac in enumerate(splits):
            amount = remaining if i == len(splits) - 1 else (total * frac).quantize(Decimal("0.01"))
            remaining -= amount
            disbursed = amount if project.status != Project.Status.PENDING else Decimal("0")
            BudgetLineItem.objects.create(
                project=project,
                description=f"{categories[i].replace('_', ' ').title()} — {project.title}",
                category=categories[i],
                approved_amount=amount,
                disbursed_amount=disbursed,
            )
        Equipment.objects.create(
            project=project,
            name=f"{project.title} — Primary Unit",
            specification="Seed data placeholder specification.",
            supplier_fabricator="Local Supplier Co.",
            acquisition_cost=(total * Decimal("0.5")).quantize(Decimal("0.01")),
            status=Equipment.Status.IN_USE,
        )

    @staticmethod
    def _add_monitoring_reports(project):
        reports = []
        if project.phase1_start_date:
            due = project.phase1_start_date + timedelta(days=150)
            submitted = due < TODAY and project.status != Project.Status.PHASE_1
            reports.append(MonitoringReport(
                project=project, report_type=MonitoringReport.ReportType.PROJECT_INFO_ONGOING,
                due_date=due, date_submitted=(due - timedelta(days=3)) if submitted else None,
            ))
        if project.refund_start_date:
            for i in range(2):
                due = project.refund_start_date + relativedelta(months=6 * (i + 1))
                # first semestral report submitted, second left open — gives
                # every Phase II project at least one "not yet due or still
                # outstanding" report to look at, some of which will show as
                # overdue depending on how far past due_date TODAY is.
                submitted = (i == 0) and due < TODAY
                reports.append(MonitoringReport(
                    project=project, report_type=MonitoringReport.ReportType.SEMESTRAL_STATUS,
                    period_covered=f"Semester {i + 1}",
                    due_date=due, date_submitted=(due - timedelta(days=5)) if submitted else None,
                ))
        if project.status == Project.Status.COMPLETED:
            reports.append(MonitoringReport(
                project=project, report_type=MonitoringReport.ReportType.TERMINAL,
                due_date=TODAY - timedelta(days=10), date_submitted=TODAY - timedelta(days=8),
            ))
        if project.status in (Project.Status.TERMINATED, Project.Status.WITHDRAWN):
            reports.append(MonitoringReport(
                project=project, report_type=MonitoringReport.ReportType.TERMINATION_WITHDRAWAL,
                due_date=project.termination_date or TODAY,
                date_submitted=project.termination_date or TODAY,
            ))
        MonitoringReport.objects.bulk_create(reports)

    # -- Impact KPI ---------------------------------------------------------

    def _create_impact_records(self):
        self.stdout.write("Creating Impact KPI records (last 4 quarters)...")
        quarters = ['q1', 'q2', 'q3', 'q4']
        this_quarter_index = (TODAY.month - 1) // 3
        for offset in range(4, 0, -1):
            idx = this_quarter_index - offset
            year = TODAY.year + (idx // 4)
            quarter = quarters[idx % 4]
            baseline = ImpactRecord.compute_project_estimate(year, quarter)
            ImpactRecord.objects.get_or_create(
                year=year, quarter=quarter,
                defaults=dict(
                    **baseline,
                    gross_sales=Decimal(random.randint(500, 4000) * 1000),
                    remarks="Seed data — baseline auto-computed, gross sales estimated.",
                ),
            )

    # -- Test accounts --------------------------------------------------------

    def _create_demo_users(self):
        self.stdout.write("Creating demo accounts...")
        User = get_user_model()

        if not User.objects.filter(username='admin').exists():
            User.objects.create_superuser('admin', 'admin@example.com', 'DostSetup2026!')
            self.stdout.write("  Superuser  -> username: admin       password: DostSetup2026!")

        if not User.objects.filter(username='staff').exists():
            staff = User.objects.create_user(
                'staff', 'staff@example.com', 'DostSetup2026!',
                first_name='Staff', last_name='Demo', is_staff=True,
            )
            staff.save()
            self.stdout.write("  Staff      -> username: staff       password: DostSetup2026!")

        if not User.objects.filter(username='viewer').exists():
            User.objects.create_user(
                'viewer', 'viewer@example.com', 'DostSetup2026!',
                first_name='Viewer', last_name='Demo',
            )
            self.stdout.write("  Non-staff  -> username: viewer      password: DostSetup2026!")