# Generated by Django 5.2.15 on 2026-07-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrealignment',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='budget_realignments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='refundpayment',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='refund_receipts/%Y/%m/', verbose_name='Scanned O.R.'),
        ),
        migrations.AddField(
            model_name='refundrestructure',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='refund_restructures/%Y/%m/'),
        ),
    ]
