# Generated by Django 5.2.15 on 2026-07-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_cooperator_options_alter_project_cooperator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='project_photos/%Y/%m/'),
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
