# Generated by Django 5.2.15 on 2026-07-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_project_photo_delete_projectimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectrequirement',
            options={'ordering': ['phase', 'requirement_type']},
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='phase',
            field=models.CharField(choices=[('phase_1', 'Required before Phase I'), ('phase_2', 'Required before Phase II'), ('completed', 'Required before Completion')], default='phase_1', help_text='Which status this requirement must be completed before the project can enter.', max_length=15),
        ),
        migrations.AlterField(
            model_name='projectrequirement',
            name='requirement_type',
            field=models.CharField(choices=[('letter_of_intent', 'Letter of Intent'), ('tna_form_01', 'DOST TNA Form 01 - Application for TNA'), ('tna_form_02', 'DOST TNA Form 02 - TNA Report'), ('proposal', 'SETUP Form 001 - Project Proposal'), ('business_permit', 'Business Permits/Licenses'), ('registration_cert', 'DTI/SEC/CDA Registration'), ('official_receipt', 'Official Receipt (photocopy)'), ('articles_of_incorporation', 'Articles of Incorporation'), ('board_resolution', 'Board/Council Resolution'), ('financial_statements', 'Financial Statements (past 1-3 yrs)'), ('sworn_affidavit', 'Sworn Affidavit (no conflict of interest)'), ('projected_financials', 'Projected Financial Statements'), ('technical_specs', 'Technical Specifications/Drawings'), ('supplier_quotations', 'Supplier Quotations (min. 3)'), ('phase1_completion_report', 'SETUP Form 010 - Completion Report'), ('phase1_financial_report', 'SETUP Form 004 - Audited Financial Report (Phase I)'), ('terminal_report', 'SETUP Form 013 - Terminal Report'), ('other', 'Other')], max_length=30),
        ),
    ]
