# Generated by Django 5.2.15 on 2026-07-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_alter_impactrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperator',
            name='is_export_firm',
            field=models.BooleanField(default=False, help_text='Whether this MSME is engaged in exporting.', verbose_name='Export Firm'),
        ),
        migrations.AddField(
            model_name='project',
            name='jobs_created',
            field=models.PositiveIntegerField(default=0, help_text='Jobs created as a direct result of this project (warm bodies).', verbose_name='Jobs Created'),
        ),
    ]
