# Generated by Django 5.2.15 on 2026-07-27 08:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('corporation', 'Corporation'), ('cooperative', 'Cooperative'), ('industry_association', 'Industry Association'), ('lgu', 'Local Government Unit'), ('suc', 'State University/College'), ('other', 'Other')], max_length=30)),
                ('enterprise_category', models.CharField(blank=True, choices=[('micro', 'Micro'), ('small', 'Small'), ('medium', 'Medium')], max_length=10)),
                ('development_stage', models.CharField(blank=True, choices=[('developing', 'Developing Enterprise'), ('growing', 'Growing Enterprise'), ('expanding', 'Expanding and Innovating Enterprise')], max_length=15)),
                ('priority_sector', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dti_sec_cda_registration_no', models.CharField(blank=True, max_length=100, verbose_name='DTI/SEC/CDA Registration No.')),
                ('filipino_ownership_percent', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Must be at least 60% per eligibility requirements.', max_digits=5)),
                ('has_outstanding_accountabilities', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('project_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('phase_1', 'Phase I - Implementation'), ('phase_2', 'Phase II - Refund Period'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('withdrawn', 'Withdrawn')], default='pending', max_length=15)),
                ('total_ifund_amount', models.DecimalField(decimal_places=2, help_text='Total amount of funding assistance approved (the principal to be refunded).', max_digits=14, verbose_name='Total iFund Support (₱)')),
                ('fund_source', models.CharField(choices=[('setup_budget', 'SETUP Budget (refundable)'), ('lgia', 'Local GIA (non-refundable)')], default='setup_budget', max_length=20)),
                ('phase1_start_date', models.DateField(blank=True, help_text='Date SETUP funds were received.', null=True)),
                ('phase1_expected_end_date', models.DateField(blank=True, help_text='6–12 months from phase1_start_date per AO guidelines.', null=True)),
                ('phase1_actual_end_date', models.DateField(blank=True, null=True)),
                ('refund_period_years', models.PositiveSmallIntegerField(blank=True, choices=[(3, '3 years'), (5, '5 years')], null=True)),
                ('refund_start_date', models.DateField(blank=True, help_text='Commences after Phase I completion.', null=True)),
                ('refund_extension_years', models.PositiveSmallIntegerField(default=0, help_text='Max 2 additional years allowed.', validators=[django.core.validators.MaxValueValidator(2)])),
                ('budget_realignment_count', models.PositiveSmallIntegerField(default=0)),
                ('implementation_date_changed', models.BooleanField(default=False)),
                ('termination_reason', models.CharField(blank=True, choices=[('force_majeure', 'Force Majeure / Fortuitous Event'), ('default', "Cooperator's Failure/Neglect"), ('death', 'Death of Cooperator'), ('other', 'Other')], max_length=20)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('final_obligation_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Computed per Annex B for terminated/withdrawn projects.', max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooperator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='monitoring.cooperator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('form_003', 'Form 003 - Semestral Status Report'), ('form_009', 'Form 009 - Project Info Sheet (Ongoing)'), ('form_010', 'Form 010 - Completion Report'), ('form_004', 'Form 004 - Audited Financial Report'), ('form_012', 'Form 012 - Annual Refund Performance Report'), ('form_013', 'Form 013 - Terminal Report'), ('form_011', 'Form 011 - Termination/Withdrawal Report')], max_length=15)),
                ('period_covered', models.CharField(blank=True, help_text="e.g. 'H1 2026', 'FY 2026'", max_length=100)),
                ('due_date', models.DateField()),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='monitoring_reports/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_reports', to='monitoring.project')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specification', models.TextField(blank=True)),
                ('supplier_fabricator', models.CharField(blank=True, max_length=255)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('in_use', 'In Use at Cooperator'), ('pulled_out', 'Pulled Out'), ('transferred', 'Transferred to New Cooperator'), ('donated', 'Donated'), ('disposed', 'Disposed'), ('owned', 'Ownership Transferred (Fully Refunded)')], default='in_use', max_length=20)),
                ('pulled_out_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='monitoring.project')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetRealignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realignments', to='monitoring.project')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('equipment', 'Equipment'), ('training', 'Training'), ('lab_analysis', 'Laboratory Analysis'), ('packaging_labeling', 'Packaging/Labeling'), ('consultancy', 'Consultancy'), ('other', 'Other')], default='equipment', max_length=30)),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='monitoring.project')),
            ],
        ),
        migrations.CreateModel(
            name='RefundInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('waived', 'Waived'), ('restructured', 'Restructured')], default='unpaid', max_length=15)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_installments', to='monitoring.project')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='RefundPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_paid', models.DateField(default=django.utils.timezone.now)),
                ('or_number', models.CharField(blank=True, max_length=100, verbose_name='O.R. / Reference No.')),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='monitoring.refundinstallment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_payments', to='monitoring.project')),
            ],
        ),
        migrations.CreateModel(
            name='RefundRestructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground', models.CharField(choices=[('delay', 'Delay in Project Implementation'), ('calamity', 'Natural Calamity'), ('technical', 'Technical Difficulties with Equipment'), ('regulation', 'New Rules/Regulations'), ('industry', 'Industry-related Problem'), ('other', 'Other (RTEC-recommended)')], max_length=15)),
                ('requested_date', models.DateField(default=django.utils.timezone.now)),
                ('new_schedule_notes', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restructures', to='monitoring.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('letter_of_intent', 'Letter of Intent'), ('tna_form_01', 'DOST TNA Form 01 - Application for TNA'), ('tna_form_02', 'DOST TNA Form 02 - TNA Report'), ('proposal', 'SETUP Form 001 - Project Proposal'), ('business_permit', 'Business Permits/Licenses'), ('registration_cert', 'DTI/SEC/CDA Registration'), ('official_receipt', 'Official Receipt (photocopy)'), ('articles_of_incorporation', 'Articles of Incorporation'), ('board_resolution', 'Board/Council Resolution'), ('financial_statements', 'Financial Statements (past 1-3 yrs)'), ('sworn_affidavit', 'Sworn Affidavit (no conflict of interest)'), ('projected_financials', 'Projected Financial Statements'), ('technical_specs', 'Technical Specifications/Drawings'), ('supplier_quotations', 'Supplier Quotations (min. 3)'), ('other', 'Other')], max_length=30)),
                ('is_submitted', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='project_requirements/%Y/%m/')),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='monitoring.project')),
            ],
            options={
                'ordering': ['requirement_type'],
                'unique_together': {('project', 'requirement_type')},
            },
        ),
    ]
