# Generated by Django 5.2.15 on 2026-07-28 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_budgetrealignment_supporting_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooperator',
            options={'verbose_name': 'MSME', 'verbose_name_plural': 'MSMEs'},
        ),
        migrations.AlterField(
            model_name='project',
            name='cooperator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='monitoring.cooperator', verbose_name='MSME'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='monitoring.project')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
