# Generated by Django 5.2.15 on 2026-07-30 04:38

import django.db.models.deletion
import django.utils.timezone
import monitoring.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_projectrequirement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=monitoring.models._current_year)),
                ('quarter', models.CharField(choices=[('q1', 'Q1 (Jan–Mar)'), ('q2', 'Q2 (Apr–Jun)'), ('q3', 'Q3 (Jul–Sep)'), ('q4', 'Q4 (Oct–Dec)')], max_length=2)),
                ('jobs_created', models.PositiveIntegerField(default=0, help_text='Jobs created attributable to this project this quarter.')),
                ('technologies_used', models.PositiveIntegerField(default=0, help_text='Number of technology interventions applied this quarter.')),
                ('is_export_firm', models.BooleanField(default=False, help_text='Whether the MSME was exporting as of this quarter.')),
                ('gross_sales', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="MSME's reported gross sales for this quarter.", max_digits=14, verbose_name='Gross Sales (₱)')),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_records', to='monitoring.project')),
            ],
            options={
                'ordering': ['-year', '-quarter'],
                'unique_together': {('project', 'year', 'quarter')},
            },
        ),
    ]
