# Generated by Django 5.2.15 on 2026-07-30 04:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_impactrecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='impactrecord',
            unique_together={('year', 'quarter')},
        ),
        migrations.AddField(
            model_name='impactrecord',
            name='entities_assisted',
            field=models.PositiveIntegerField(default=0, help_text='Please include the walk-in clients.', verbose_name='No. of firms/other S&T entities provided with S&T assistance'),
        ),
        migrations.AddField(
            model_name='impactrecord',
            name='export_firms_assisted',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of export firms assisted'),
        ),
        migrations.AddField(
            model_name='impactrecord',
            name='technology_interventions',
            field=models.PositiveIntegerField(default=0, verbose_name='No. of technology interventions'),
        ),
        migrations.AlterField(
            model_name='impactrecord',
            name='gross_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, verbose_name='Gross Sales (in Pesos)'),
        ),
        migrations.AlterField(
            model_name='impactrecord',
            name='jobs_created',
            field=models.PositiveIntegerField(default=0, verbose_name='No. of jobs created (in terms of warm bodies)'),
        ),
        migrations.AlterField(
            model_name='impactrecord',
            name='quarter',
            field=models.CharField(choices=[('q1', '1st Quarter'), ('q2', '2nd Quarter'), ('q3', '3rd Quarter'), ('q4', '4th Quarter')], max_length=2),
        ),
        migrations.RemoveField(
            model_name='impactrecord',
            name='is_export_firm',
        ),
        migrations.RemoveField(
            model_name='impactrecord',
            name='project',
        ),
        migrations.RemoveField(
            model_name='impactrecord',
            name='technologies_used',
        ),
    ]
