# Generated by Django 5.2.15 on 2026-08-03 02:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_cooperator_is_export_firm_project_jobs_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gross_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="This MSME's self-reported gross sales attributable to this project.", max_digits=16, verbose_name='Gross Sales (₱)'),
        ),
    ]
