# Generated by Django 5.2.15 on 2026-08-03 06:00

import django.db.models.deletion
import monitoring.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_project_gross_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectQuarterlyImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=monitoring.models._current_year)),
                ('quarter', models.CharField(choices=[('q1', '1st Quarter'), ('q2', '2nd Quarter'), ('q3', '3rd Quarter'), ('q4', '4th Quarter')], max_length=2)),
                ('jobs_created', models.PositiveIntegerField(default=0, help_text='Jobs created by this project DURING this specific quarter — not a running lifetime total.', verbose_name='Jobs Created This Quarter')),
                ('gross_sales', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="This MSME's gross sales attributable to this project, earned DURING this specific quarter.", max_digits=16, verbose_name='Gross Sales This Quarter (₱)')),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_impacts', to='monitoring.project')),
            ],
            options={
                'verbose_name': 'Project Quarterly Impact',
                'verbose_name_plural': 'Project Quarterly Impacts',
                'ordering': ['-year', '-quarter'],
                'unique_together': {('project', 'year', 'quarter')},
            },
        ),
    ]
