# Generated by Django 5.2.15 on 2026-08-03 08:03

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_projectquarterlyimpact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectquarterlyimpact',
            options={'ordering': ['-year', '-quarter']},
        ),
        migrations.RemoveField(
            model_name='projectquarterlyimpact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projectquarterlyimpact',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='projectquarterlyimpact',
            name='date_recorded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='gross_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="MSME's current reported gross sales attributable to this project.", max_digits=14, verbose_name='Gross Sales (₱)'),
        ),
        migrations.AlterField(
            model_name='projectquarterlyimpact',
            name='gross_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='projectquarterlyimpact',
            name='jobs_created',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
