# Generated by Django 5.2.15 on 2026-08-04 02:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_alter_projectquarterlyimpact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_ifund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Total amount of funding assistance approved (the principal to be refunded). Leave blank until the approved amount is confirmed — defaults to ₱0 rather than being left null, since remaining_balance/refund_progress_percent below do arithmetic on this field and a real None would crash them.', max_digits=14, verbose_name='Total iFund Support (₱)'),
        ),
    ]
